# Generated by Django 5.0 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core.users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Cancelar ao Fim do Período'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Teste'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Teste'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='default_payment_method_last4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='default_payment_method_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bandeira'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='default_payment_method_exp_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mês de Expiração'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='default_payment_method_exp_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Expiração'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grace Period até'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(
                choices=[
                    ('trialing', 'Em Teste'),
                    ('active', 'Ativa'),
                    ('past_due', 'Pagamento Atrasado'),
                    ('canceled', 'Cancelada'),
                    ('unpaid', 'Não Pago'),
                    ('incomplete', 'Incompleta'),
                    ('incomplete_expired', 'Incompleta Expirada'),
                ],
                default='active',
                max_length=20,
                verbose_name='Status'
            ),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe Invoice ID')),
                ('stripe_customer_id', models.CharField(max_length=100, verbose_name='Stripe Customer ID')),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Rascunho'),
                        ('open', 'Aberta'),
                        ('paid', 'Paga'),
                        ('uncollectible', 'Não Cobrável'),
                        ('void', 'Anulada'),
                    ],
                    default='open',
                    max_length=20,
                    verbose_name='Status'
                )),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Restante')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Fatura')),
                ('invoice_pdf', models.URLField(blank=True, max_length=500, null=True, verbose_name='PDF da Fatura')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paga em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.users.subscription')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
